// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WuoWDQxn6cBL9r3Oe_FnC3N4YpJmQbw',
    appId: '1:505501066611:web:c10b5c7633fae8171b5106',
    messagingSenderId: '505501066611',
    projectId: 'kakashi-2bf36',
    authDomain: 'kakashi-2bf36.firebaseapp.com',
    storageBucket: 'kakashi-2bf36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQLG4MjjBFrW2ecYTafwyBGOMtaqRgnDU',
    appId: '1:505501066611:android:31385f735f4dc63e1b5106',
    messagingSenderId: '505501066611',
    projectId: 'kakashi-2bf36',
    storageBucket: 'kakashi-2bf36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM0SkZFNS4hFmTPHg8BH9AE6CT8cyABl4',
    appId: '1:505501066611:ios:65bffe00ad672c181b5106',
    messagingSenderId: '505501066611',
    projectId: 'kakashi-2bf36',
    storageBucket: 'kakashi-2bf36.appspot.com',
    iosClientId: '505501066611-fadmm65p14cmlsn8259ds9rndvbobj97.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakashi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM0SkZFNS4hFmTPHg8BH9AE6CT8cyABl4',
    appId: '1:505501066611:ios:65bffe00ad672c181b5106',
    messagingSenderId: '505501066611',
    projectId: 'kakashi-2bf36',
    storageBucket: 'kakashi-2bf36.appspot.com',
    iosClientId: '505501066611-fadmm65p14cmlsn8259ds9rndvbobj97.apps.googleusercontent.com',
    iosBundleId: 'com.example.kakashi',
  );
}
